<!doctype html><html lang="ru"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="author" content="Детский портал - Малыш"><link rel="author" href="https://plus.google.com/110711708448558111115"><meta name="copyright" lang="ru" content="Детский портал - Малыш"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="index,follow"/><meta name='yandex-verification' content='676d839988d26fd4' /><meta name="google-site-verification" content="Yh5DA-OcppOsdnExEFTRjpGHacy3RfbgFSVxBzgfTbI" /><meta name="msvalidate.01" content="D14FC18510E967FDCF86B7B1BACA6D6C" /><meta name='wmail-verification' content='973142ad1f6722e4f1d4d613f8482f42' /><link rel="shortcut icon" href="/img/site/ico.png" type="image/png"><link rel="stylesheet" type="text/css" href="/css/css.php?v1">

    <link rel="stylesheet" type="text/css" href="/css/testy.css">

    <link rel="stylesheet" type="text/css" href="/css/loader.css">

    <script async src="/js/jq.php?v1" type="text/javascript"></script><script async src="/js/common.php?v1"></script><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><meta name="description" content="Изучение математики стало интерактивнее. Методики обучения вычитанию реализованы для облегчения привлечения дитя к арифметике. При выполнении задания необходимо выбрать ответ..."><meta name="keywords" content="математика, вычитание, методики вычитания, математика вычитание, обучение, варианты ответа, с вариантами ответа"><title>Вычитание с вариантами ответа - математика - сайт для детей</title></head><body><div id="bh" class="maxw"><div class="cl"></div></div><div id="header" class="maxw"><header><div id="logo" class="fl rel"><a href="/"><img src="/img/site/png.php?img=logo" alt="Логотип" title="На главную"></a><div class="cl"></div></div>
        <div class="h_field"><!--сказ--><div id="skazki" class="fr v_menu"><div class="v_menu_link"><div class="ac"><a href="/сказки/"><img src="/img/site/jpg.php?img=skazki" alt="Сказки"></a></div><p>Выберите раздел:</p><nav><ul><li><a href="/сказки/русские/">Русский кинематограф</a></li><li><a href="/сказки/зарубежные/">Зарубежный кинематограф</a></li></ul></nav></div><div class="v_menu_btn">Сказки</div></div><!--мульт--><div id="mult" class="fr v_menu"><div class="v_menu_link"><div class="ac"><a href="/мультики/"><img src="/img/site/jpg.php?img=vinni_mult" alt="Мультфильмы"></a></div><p>Выберите раздел:</p><nav><ul><li><a href="/мультики/российские/">Российские - современные</a></li><li><a href="/мультики/советские/">Советские</a></li><li><a href="/мультики/для-малышей/">Для малышей</a></li></ul></nav></div><div class="v_menu_btn">Мультфильмы</div></div><!--/мульт--><div class="cl"></div></div>
        <div class="h_field">&nbsp;<div class="cl"></div></div>
        <div class="cl"></div></header></div><div id="ah" class="maxw"><div class="cl"></div></div><div id="wrap" class="maxw"><div id="l_col" class="fl rel"><div class="l_menu rel"><div class="l_menu_title">Игровая</div><nav><ul><li><a href="/лабиринты-распечатать/">Лабиринты на печать</a></li></ul></nav></div><div class="l_menu rel"><div class="l_menu_title">Математика</div><nav><ul><li><a href="/математика/соседи-числа/">Соседи числа</a></li><li><a href="/математика/сложение/">Сложение</a></li><li><a href="/математика/вычитание/">Вычитание</a></li></ul></nav></div><div class="l_menu rel"><div class="l_menu_title">Обучающие слайды</div><nav><ul><li><a href="/обучающие-слайды/алфавит-звуки-и-буквы/">Алфавит, звуки и буквы</a></li><li><a href="/обучающие-слайды/цифры-и-математика/">Цифры и математика</a></li></ul></nav></div><div class="l_menu rel"><div class="l_menu_title">Юмор</div><nav><ul><li><a href="/устами-младенца/">Устами младенца</a></li></ul></nav></div><div class="cl"></div></div><div id="m_col" class="rel"><!--Пр кол--><div id="r_col" class="fr rel"><div class="r_menu rel"><div class="r_menu_title">Доп.материалы</div><nav><ul><li><a href="/скороговорки-для-малышей">Скороговорки для малышей</a></li><li><a href="/считалки/">Считалочки</a></li><li><a href="/колыбельные/">Колыбельные песенки</a></li></ul></nav></div><div class="r_menu rel"><div class="r_menu_title">Беременность и роды</div><nav><ul><li><a href="/беременность/планирование/">Планирование, подготовка</a></li><li><a href="/беременность/красота/">Красота и уход</a></li><li><a href="/беременность/здоровье/">Забота о здоровье</a></li></ul></nav></div><div class="r_menu rel"><div class="r_menu_title">Уход за младенцем</div><nav><ul><li><a href="/новорожденный/">Новорожденный</a></li><li><a href="/детское-здоровье/">Детское здоровье</a></li><li><a href="/советы-родителям/">Советы родителям</a></li></ul></nav></div><div class="cl"></div></div><!--Центр кол--><div id="c_col" class="rel"><main>

                <div id="teststart" class="testanswerbtn" data-test="Пикс">Ответ</div>

                <!--div class="fon rel test">
                    <img class="board" src="/img/mat/jpg.php?img=board">
                    <div class="testbody">
                        <div class="testres"></div>
                        <div class="testquestion"><p>Здесь вы должны решить математические задачи на нахождение суммы для 1 класса. В тесте - 10 вопросов-задач</p></div>
                        <div class="testwarning">Пожалуйста, ответьте на данный вопрос</div>
                        <div class="testanswer"><input id="testanswer" type="text"></div>
                        <div id="teststart" class="testanswerbtn">Ответ</div>
                        <div class="testflash">jo</div>
                    </div>
                <div class="cl"></div></div>-->
                <!--<div id="floatBarsG">
                    <div id="floatBarsG_1" class="floatBarsG"></div>
                    <div id="floatBarsG_2" class="floatBarsG"></div>
                    <div id="floatBarsG_3" class="floatBarsG"></div>
                    <div id="floatBarsG_4" class="floatBarsG"></div>
                    <div id="floatBarsG_5" class="floatBarsG"></div>
                    <div id="floatBarsG_6" class="floatBarsG"></div>
                    <div id="floatBarsG_7" class="floatBarsG"></div>
                    <div id="floatBarsG_8" class="floatBarsG"></div>
                </div>-->

                <script src="/js/test/test_common.js"></script>

                <div class="cl"></div></main><div class="cl"></div></div><!--Конец Центр кола--><div class="cl"></div></div><!--end m_col--><div class="cl"></div></div><!--end maxw--><div id="bf" class="maxw"><div class="cl"></div></div><div id="foot" class="rel"><footer><div class="footmenu"><nav><ul><li><a href="/обратная-связь">Обратная связь</a></li></ul></nav><div class="cl"></div></div><div id="share" class="nav_link"><!--g+1--><div class="rel fl"><div class="g-plusone" data-annotation="none"></div></div><script type="text/javascript">window.___gcfg={lang:'ru'};(function(){var po=document.createElement('script');po.type='text/javascript';po.async=true;po.src='https://apis.google.com/js/platform.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po,s);})();</script><div class="rel fl"><div class="ya-share2" data-services="twitter,facebook,vkontakte,odnoklassniki,moimir,lj"></div></div><div class="cl"></div></div><div id="copy" class="ac">Copyright &copy;dp.my - Детский портал - &laquo;Малыш&raquo; 2015-2016<br><br>Использование материалов сайта без разрешения правообладателя запрещено</div><div id="informer" class="ac"><span id="yandex"><!--Ya.Met--><a href="https://metrika.yandex.ru/stat/?id=33489788&amp;from=informer" target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/33489788/3_0_FFFFFFFF_FEFEE2FF_0_pageviews" style="width:88px; height:31px;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:33489788,lang:'ru'});return false}catch(e){}" /></a><script type="text/javascript">(function(d,w,c){(w[c]=w[c] || []).push(function(){try{w.yaCounter33489788=new Ya.Metrika({id:33489788,clickmap:true,trackLinks:true,accurateTrackBounce:true,webvisor:true,trackHash:true});}catch(e){}});var n = d.getElementsByTagName("script")[0],s=d.createElement("script"),f=function(){n.parentNode.insertBefore(s,n);};s.type="text/javascript";s.async=true;s.src="/js/ya_metrika.php";if(w.opera=="[object Opera]"){d.addEventListener("DOMContentLoaded",f,false);}else{f();}})(document,window,"yandex_metrika_callbacks");</script><!--/Ya.Met--></span></div><div id="up"> ^ Наверх </div><div class="cl"></div></footer></div><link rel="stylesheet" type="text/css" href="/css/mat.css"><!--0.095145c--></body></html>